# mosquitto/mosquitto.conf
listener 1883
# Permitir conexiones sin usuario/contraseña (Solo para desarrollo local)
allow_anonymous true

# Si más adelante quieres conectar React directamente al MQTT por WebSockets:
listener 9001
protocol websockets